language: node_js
node_js:
  - "10"
script:
  - yarn build
deploy:
  provider: script
  script: 
    - cp package.json build
    - cp yarn.lock build
    - cp now.json build
    - yarn deploy
  skip_cleanup: true
  on:
    branch: master